// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace empclass
{
    public partial class Attendecee
    {
        public int AttendId { get; set; }
        public string Mail { get; set; }
        public int? Employeeid { get; set; }
        public string Fullname { get; set; }
        public DateTime? Pdate { get; set; }
        public string Astatus { get; set; }

        public virtual Register Employee { get; set; }
    }
}