// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace empclass
{
    public partial class Leave
    {
        public int Leaveid { get; set; }
        public int? Employeeid { get; set; }
        public DateTime? Fromdate { get; set; }
        public DateTime? Todate { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }

        public virtual Register Employee { get; set; }
    }
}