// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace empclass
{
    public partial class Register
    {
        public Register()
        {
            Attendecees = new HashSet<Attendecee>();
            Leaves = new HashSet<Leave>();
            Salaries = new HashSet<Salary>();
        }

        public int Employeeid { get; set; }
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public long? Mobile { get; set; }
        public string Passwords { get; set; }
        public string Designation { get; set; }
        public string Address1 { get; set; }
        public string Gender { get; set; }
        public string States { get; set; }
        public string City { get; set; }
        public DateTime? Dob { get; set; }
        public string Pincode { get; set; }

        public virtual ICollection<Attendecee> Attendecees { get; set; }
        public virtual ICollection<Leave> Leaves { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}