// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace empclass
{
    public partial class Salary
    {
        public int Salaryid { get; set; }
        public int? Employeeid { get; set; }
        public decimal? Basicpay { get; set; }
        public decimal? Allowence { get; set; }
        public decimal? Hra { get; set; }
        public decimal? Medicalallowence { get; set; }
        public decimal? Bonus { get; set; }
        public decimal? Pf { get; set; }
        public decimal? Professionaltax { get; set; }
        public decimal? Netsalary { get; set; }

        public virtual Register Employee { get; set; }
    }
}